export const BLACKLISTED_CHANNELS = new Set([
     "Daily_Writeups","thehackernews","SamsonUpdate", "jalwagameshack", "Udemy4U", "SamsungCommunity", "indianexpress", "BCA_official", "mppscadda", "seekerasjob", "gizchinacom",
     "ctftimeorg_events", "iphone_unl", "devsirga", "efxtv", "technicalnavigator", "TEAMRSSIR", "TechOfficeUpdate",
     "pritipaper1", "lsvirtualassistant", "buzz2daytech", "niliet_ccc_exam_preparation", "JonDowling", "Kaori_watermelon",
     "NOALLO", "Nyakundi", "HuaweiCentral", "TheIslanderNews", "ScottRitter", "gistapapapa", "Reality_Theories",
     "UA_1NEWS", "bovind", "writingsamurai", "AussieCossack", "thecradlemedia", "fcsitunimas", "OPENVACANCIES2022",
     "unfolded", "ukr_leaks_eng", "englishabuali", "zoka200", "geromanat", "MFARussia", "thetimeskuwait",
     "kaidensharmaa", "JoinSSBCrack", "wolprotest", "WOLProtest", "ForsvaretTelegram", "teamarpitssbguide", "zeeemedia",
     "manalaexmanakosam", "krispotupchik", "BadVolfNews", "mjsdefenceacademy", "LiteratureLoversTelegram",
     "unacademyofflinecentre", "freechesscourses", "thedailyhodl", "mediumcom", "SAP_BASIS_TIPS_RU", "count0_digest",
     "s_e_book", "Huduma", "EnextUdemyCoupons", "FreeTutorial", "aioftheday", "tokenmetrics", "dotjobs",
     "channelairdropsnews", "gizchinait", "jobsinternshipswale", "udemyforu", "ExamkeyNet", "techpicks",
     "MasoudOstadChannel", "coursejoiner", "addis_ken", "freeudemycourses4uall", "Coursevania", "onlinecourses_free",
     "udemycoursesfree", "freshersvoice", "deadlawyers", "alljobspo_ghana", "camonk8", "dot_aware", "jobs4fresherdotcom",
     "fresherearth", "placementdrive_pld", "edubard", "kriptoparahaber", "ted_talks", "usfofficial", "techandtarget",
     "bestlviv", "skoltech_daily", "ptionalsocio", "Ganitmanch", "ThePundits_Official", "equitymasterofficial",
     "cagurujii", "caiibwithashok", "ContactDeepak", "codinglogic", "jobs4engineers", "placementhelp", "s32_content",
     "placementdriveofficial", "liquideofficial", "karnatakagovtjobonline", "keralagovtjobonline",
     "telanganagovernmentjobs", "CHOICEOPTION", "SR_CricketFantasy", "allcourses_2025", "Economics_MPSC",
     "yashkhandelwaldt", "mgsirmaths", "Gwcomsciandinfo", "sign2tech", "first_places", "sreedharjalapatiaptitudeclasses",
     "litegameyt", "OneStepTradingAcademy", "CA_Study_Notes", "GTC_Consulting_Team_Unbeatable", "sammyfans", "joblens",
     "lawbhoomi", "LevelEightyNews", "recoveryteamchannel", "dilbert_scott_adams", "breachdetector", "apgovtjobonline",
     "goyalarsh", "dailymonitor", "indiafastJobAlert", "JFK_Q17", "FabrizioRomanoTG", "helloyaponiya",
     "rajasthangovernmentjobsupdates", "classes_by_pythonhub", "jobsearchghana", "XiaomiMIUIUpdates",
     "english_with_paul_newson", "udemyoff", "FreeUdemyCourses4All", "coursecouponclub", "llordofwar", "FiorellaInMoscow",
     "alzaytounaEN", "TheWealthMagnet", "watcherguru", "RegjeringenVideos", "eng_omar_khamis", "gyanshilaSid", "Miatoll",
     "pilotblog", "coingraphnews", "paget96_projects_channel", "toresaysPlus", "oliverjanich", "trickybankernewchannel",
     "fortunatesailors", "chandrapeela", "SRISAINEETPG", "TNPSC_OFFICE", "learnwithmansi", "updates", "media", "print",
     "jobs", "job", "fans", "paper", "exam", "class", "placement", "affairs", "currentaffairs", "tutorial", "vacancy",
     "result", "course", "IAS", "classes", "education", "cricket", "football", "shuhaibchannel", "officialresultbharat",
     "educatiionnewsrajasthan", "jobmaama", "WINSHINEIASYOUTUBE", "smartlearningacademy", "GSET_Paper_1",
     "nextiasofficial", "exampediia", "seekeras", "NekrajCricket", "Yolo247", "study_vikram", "study", "RahulGandhi",
     "pahulwalia", "MarketLoad101", "VIJAYAVANI", "jayjaygarvigujrat", "ClearCAWithSK", "paytmmisscallloot",
     "akashthedeveloper", "todaysportsmelbet", "sports", "Goldsbet_VIP", "DivyaGTandon", "AIBEAofficial",
     "Mechanical_job_openings", "TheCaduceusOfficial", "PunchNewspaper", "phantasm_lab", "BloodMOONScript",
     "crazygktrick_official_channel", "noname05716eng", "RuSecJobs", "xqYr2voJ5980OTA1", "anonymoustutorials",
     "devukraine", "dani_apps", "mathrubhumienglish", "application_SA", "tech_ninjas_imsec", "itiunofficial",
     "ThePirateZone", "govtechbytes", "upsciassquad", "Santoshkumarcurrentaffairs", "ptswarm", "nzdsos", "FreedomDoc1",
     "shadowseekers5", "kryptonzambie", "spmias", "phpproglib", "pemburutiketmurah", "cnalatest", "casusbellilive",
     "verkhovnaradaofukraine", "i20028843", "cgtn_europe", "WarriorsUkrainian", "DefenseForcesVideos", "chessforallll",
     "noel_reports", "insightssb", "mortisaeterna", "Empire_MU", "dgpindia", "DSquadOfficial", "attack_full_moviess",
     "pravdagerashchenko_en", "ingliztili_audiolar", "v0indexnews", "aljazeeraglobal", "m2ensenChannel", "tironianae",
     "arbuz_lovers", "ValleySchool", "day_bye_day", "rvision_pro", "fishing_daily", "patricklancasternewstoday", "medmannews",
     "jalwagameshack", "visionwbcs", "UtpalPandey", "news4hack", "madhukarsirofficial"
]);

export const otpChannels = [
     "otp_store_tm",
     "itsmealexaliza",
     "ACPBuyers",
     "JoinLLA",
     "HackerSocietyT",
     "DOSSCHAT",
     "LMX_Main",
     "BOLE0003",
     "BreachLeakData",
     "CyberSecAM",
     "pw_thor",
     "wus_team",
     "cryptofiii",
     "blacksoftaz",
     "aigpublicmarket"
];

/**
 * Channels whose messages are floated to the top of every result set,
 * regardless of relevance score or keyword priority. An editorial override, so
 * keep it short - anything here displaces genuine matches.
 *
 * Compared lowercase: Telegram usernames are case-insensitive, and the scraper
 * has surfaced the same channel as both "miuistuff" and "MIUIStuff".
 */
export const PINNED_CHANNELS = new Set([
  "sucai_renshe",
]);

export const predefinedChannels = [
     "OneplusAdda",
     "whyreddownloads",
     "yurichattt",
     "apkmodeldotcom",
     "sucai_renshe",
     "quanqiu_huashu_sucai",
     "DOSSCHAT",
     "biharboardallpaperleak",
     "pwn3rzs_chat",
     "AccountSquadChat",
     "AnonymousCyberWarriors",
     "BOLE0003",
     "ph4n745m_group3",
     "DataRecordsShop",
     "anonymous_Cr02x",
     "DataBreachPremium",
     "SpamoArabo",
     "SkiddieSec",
     "vxunderground",
     "CryptoHackers_Market",
     "sixtysixchat",
     "ANONYMOUS_CHAT_VIP",
     "databreachofficial",
     "GlorySec2",
     "Y4sk007",
     "Anonymous0islamic",
     "investigationAnonYmousPS",
     "aigpublicmarket",
     "youranon_storm",
     "silkroadd1",
     "Team_r70YEMEN",
     "BreachLeakData",
     "OceanLeak",
     "seekshell_com",
     "hydramarketrebuild",
     "Deathmatics",
     "+V_oM-vx0YnSN7nzH",
     "bradmax_cloud",
     "databasee01",
     "leakdataprivate",
     "PDDcp",
     "baseleak",
     "LianSec",
     "Sl1ddifree",
     "cookiecloudfree",
     "DarkSideCloud",
     "Redscritp",
     "enigmaLogS",
     "exposedghost",
     "insidehackerz",
     "afaghhosting",
     "SMokerFiles",
     "RipperSec",
     "ManticoreCloud",
     "Breachachudatabase",
     "cvv190_cloud",
     "ransomservice",
     "+uuz8-qLUNeU2ZmI0",
     "+9P5FQ85afTc4NGNl",
     "NetGhostSecurity",
     "shieldteam1",
     "illsvcleaksupload",
     "HUBHEAD",
     "+fcxhFl9JSRE3YTdi",
     "+GxHjaDP0bOphZjNh",
     "leakbase_official_v2",
     "leaksdirectory",
     "SilentForceMTB",
     "+nCFeH8PT-XUxZjEy",
     "fakesec666",
     "ridgedforums",
     "KMPteam",
     "h4shur",
     "eaglecyberwashere",
     "BLOODYSECC",
     "fckindia",
     "GrabSmtpNow",
     "killnet_reservs",
     "revolusigbanon17",
     "IranDataLeak",
     "ByteMeCrew",
     "arvinclub1",
     "TigerElectronicUnit",
     "xxShad0dexx",
     "+bGVQ-Aqmo2piZTFl",
     "YourAnonTl3x",
     "YourAnonTl3xChatGroup",
     "StableExploitvv",
     "IRoX_Team",
     "AnonCollective",
     "hackingtoolsprvi8",
     "GhostsofPs_org",
     "PaluAnonCyber",
     "KetapangGreyHatTeamV2",
     "GhostsForum",
     "TheReturnees710",
     "goblins_gang",
     "DarkStormTeamd",
     "HacktivistIndonesia",
     "HacktivistPakistan",
     "ganosecteam",
     "MysteriousTeam0",
     "Team_insane_Pakistan",
     "leadsgenerationgroup",
     "geylangescort_sgmeimei",
     "cambodiachinesejob",
     "UCloudExchange",
     "JobPostingFree",
     "XCloudTrial",
     "FrauDepartment",
     "wife_swapping_in_india_couples",
     "GoblinMarkett",
     "zzzmoney1",
     "peakymarket",
     "looking4niahriatnyebe",
     "spampro6",
     "AWSbuyandsell",
     "BANKLOGSCARDS8S",
     "onlinejobspakistan",
     "Airbnbgiftcardsflightshotel",
     "CRIMINALSELLERS"
];
