export const KEYWORDS = [
    "hack",
    "hacked",
    "leak",
    "leaked",
    "database leak",
    "DATABASE Leak",
    "breach",
    "database breach",
    "data breach",
    "malware",
    "c2",
    "trojan",
    "stealer",
    "CVE",
    "mega.nz",
    "Forums",
    "tor",
    "Leak data",
    "dos",
    "ddos",
    "anonfiles",
    "User Database",
    "sensitive",
    "internal",
    "steal",
    "drive.google.com",
    ".zip",
    "Threat",
    "Dump",
    "Mega"
  ];
  