const socialMediaLinks = [
    { name: "1337x", url: "https://www.1337x.to/user/{}" },
    { name: "2Dimensions", url: "https://2Dimensions.com/a/{}" },
    { name: "3dnews", url: "http://forum.3dnews.ru/member.php?username={}" },
    { name: "7Cups", url: "https://www.7cups.com/@{}" },
    { name: "8tracks", url: "https://8tracks.com/{}" },
    { name: "9GAG", url: "https://www.9gag.com/u/{}" },
    { name: "APClips", url: "https://apclips.com/{}" },
    { name: "About.me", url: "https://about.me/{}" },
    { name: "Academia.edu", url: "https://independent.academia.edu/{}" },
    { name: "AdmireMe.Vip", url: "https://admireme.vip/{}" },
    { name: "Air Pilot Life", url: "https://airlinepilot.life/u/{}" },
    { name: "Airbit", url: "https://airbit.com/{}" },
    { name: "Airliners", url: "https://www.airliners.net/user/{}/profile/photos" },
    { name: "All Things Worn", url: "https://www.allthingsworn.com/profile/{}" },
    { name: "AllMyLinks", url: "https://allmylinks.com/{}" },
    { name: "Amino", url: "https://aminoapps.com/u/{}" },
    { name: "AniWorld", url: "https://aniworld.to/user/profil/{}" },
    { name: "Anilist", url: "https://anilist.co/user/{}/" },
    { name: "Apple Developer", url: "https://developer.apple.com/forums/profile/{}" },
    { name: "Apple Discussions", url: "https://discussions.apple.com/profile/{}" },
    { name: "Archive of Our Own", url: "https://archiveofourown.org/users/{}" },
    { name: "Archive.org", url: "https://archive.org/details/@{}" },
    { name: "ArtStation", url: "https://www.artstation.com/{}" },
    { name: "Asciinema", url: "https://asciinema.org/~{}" },
    { name: "Ask Fedora", url: "https://ask.fedoraproject.org/u/{}" },
    { name: "AskFM", url: "https://ask.fm/{}" },
    { name: "AudioJungle", url: "https://audiojungle.net/user/{}" },
    { name: "Autofrage", url: "https://www.autofrage.net/nutzer/{}" },
    { name: "Avizo", url: "https://www.avizo.cz/{}/" },
    { name: "Blip.fm", url: "https://blip.fm/{}" },
    { name: "BOOTH", url: "https://{}.booth.pm/" },
    { name: "Bandcamp", url: "https://www.bandcamp.com/{}" },
    { name: "Bazar.cz", url: "https://www.bazar.cz/{}/" },
    { name: "Behance", url: "https://www.behance.net/{}" },
    { name: "Bezuzyteczna", url: "https://bezuzyteczna.pl/uzytkownicy/{}" },
    { name: "BiggerPockets", url: "https://www.biggerpockets.com/users/{}" },
    { name: "Bikemap", url: "https://www.bikemap.net/en/u/{}/routes/created/" },
    { name: "BioHacking", url: "https://forum.dangerousthings.com/u/{}" },
    { name: "BitBucket", url: "https://bitbucket.org/{}/" },
    { name: "Bitwarden Forum", url: "https://community.bitwarden.com/u/{}/summary" },
    { name: "Blipfoto", url: "https://www.blipfoto.com/{}" },
    { name: "Blogger", url: "https://{}.blogspot.com" },
    { name: "BodyBuilding", url: "https://bodyspace.bodybuilding.com/{}" },
    { name: "BongaCams", url: "https://pt.bongacams.com/profile/{}" },
    { name: "Bookcrossing", url: "https://www.bookcrossing.com/mybookshelf/{}/" },
    { name: "BraveCommunity", url: "https://community.brave.com/u/{}/" },
    { name: "BugCrowd", url: "https://bugcrowd.com/{}" },
    { name: "BuyMeACoffee", url: "https://buymeacoff.ee/{}" },
    { name: "BuzzFeed", url: "https://buzzfeed.com/{}" },
    { name: "CGTrader", url: "https://www.cgtrader.com/{}" },
    { name: "CNET", url: "https://www.cnet.com/profiles/{}/" },
    { name: "CSSBattle", url: "https://cssbattle.dev/player/{}" },
    { name: "CTAN", url: "https://ctan.org/author/{}" },
    { name: "Caddy Community", url: "https://caddy.community/u/{}/summary" },
    { name: "Car Talk Community", url: "https://community.cartalk.com/u/{}/summary" },
    { name: "Carbonmade", url: "https://{}.carbonmade.com" },
    { name: "Career.habr", url: "https://career.habr.com/{}" },
    { name: "Championat", url: "https://www.championat.com/user/{}" },
    { name: "Chaos", url: "https://chaos.social/@{}" },
    { name: "Chatujme.cz", url: "https://profil.chatujme.cz/{}" },
    { name: "ChaturBate", url: "https://chaturbate.com/{}" },
    { name: "Chess", url: "https://www.chess.com/member/{}" },
    { name: "Choice Community", url: "https://choice.community/u/{}/summary" },
    { name: "Clapper", url: "https://clapperapp.com/{}" },
    { name: "CloudflareCommunity", url: "https://community.cloudflare.com/u/{}" },
    { name: "Clozemaster", url: "https://www.clozemaster.com/players/{}" },
    { name: "Clubhouse", url: "https://www.clubhouse.com/@{}" },
    { name: "Code Snippet Wiki", url: "https://codesnippets.fandom.com/wiki/User:{}" },
    { name: "Codeberg", url: "https://codeberg.org/{}" },
    { name: "Codecademy", url: "https://www.codecademy.com/profiles/{}" },
    { name: "CodeChef", url: "https://www.codechef.com/users/{}" },
    { name: "Codeforces", url: "https://codeforces.com/profile/{}" },
    { name: "CodePen", url: "https://codepen.io/{}" },
    { name: "Coders Rank", url: "https://profile.codersrank.io/user/{}/" },
    { name: "Coderwall", url: "https://coderwall.com/{}" },
    { name: "Codewars", url: "https://www.codewars.com/users/{}" },
    { name: "Coinvote", url: "https://coinvote.cc/profile/{}" },
    { name: "ColourLovers", url: "https://www.colourlovers.com/lover/{}" },
    { name: "Contently", url: "https://{}.contently.com/" },
    { name: "Coroflot", url: "https://www.coroflot.com/{}" },
    { name: "Cracked", url: "https://www.cracked.com/members/{}/" },
];

export default socialMediaLinks;
